apiVersion: v1
kind: ServiceAccount
metadata:
  name: rookpp
  namespace: rookpp-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rookpp
rules:
  - apiGroups: ["storage.jackal.io"]
    resources: ["storageclusters"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["storage.jackal.io"]
    resources: ["storageclusters/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["ceph.rook.io"]
    resources: ["cephclusters", "cephblockpools", "cephfilesystems", "cephobjectstores"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rookpp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rookpp
subjects:
  - kind: ServiceAccount
    name: rookpp
    namespace: rookpp-system
