//go:build !ignore_autogenerated

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *LoopbackSpec) DeepCopyInto(out *LoopbackSpec) { *out = *in }

func (in *LoopbackSpec) DeepCopy() *LoopbackSpec {
	if in == nil {
		return nil
	}
	out := new(LoopbackSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ProvisioningSpec) DeepCopyInto(out *ProvisioningSpec) {
	*out = *in
	out.Loopback = in.Loopback
}

func (in *ProvisioningSpec) DeepCopy() *ProvisioningSpec {
	if in == nil {
		return nil
	}
	out := new(ProvisioningSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *HASpec) DeepCopyInto(out *HASpec) { *out = *in }

func (in *HASpec) DeepCopy() *HASpec {
	if in == nil {
		return nil
	}
	out := new(HASpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PoolsSpec) DeepCopyInto(out *PoolsSpec) { *out = *in }

func (in *PoolsSpec) DeepCopy() *PoolsSpec {
	if in == nil {
		return nil
	}
	out := new(PoolsSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DetectedDisk) DeepCopyInto(out *DetectedDisk) { *out = *in }

func (in *DetectedDisk) DeepCopy() *DetectedDisk {
	if in == nil {
		return nil
	}
	out := new(DetectedDisk)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageClusterSpec) DeepCopyInto(out *StorageClusterSpec) {
	*out = *in
	out.Provisioning = in.Provisioning
	out.HA = in.HA
	out.Pools = in.Pools
}

func (in *StorageClusterSpec) DeepCopy() *StorageClusterSpec {
	if in == nil {
		return nil
	}
	out := new(StorageClusterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageClusterStatus) DeepCopyInto(out *StorageClusterStatus) {
	*out = *in
	if in.DetectedDisks != nil {
		out.DetectedDisks = make([]DetectedDisk, len(in.DetectedDisks))
		copy(out.DetectedDisks, in.DetectedDisks)
	}
	if in.HAEligibleSince != nil {
		t := in.HAEligibleSince.DeepCopy()
		out.HAEligibleSince = t
	}
	if in.Conditions != nil {
		out.Conditions = make([]v1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}

func (in *StorageClusterStatus) DeepCopy() *StorageClusterStatus {
	if in == nil {
		return nil
	}
	out := new(StorageClusterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageCluster) DeepCopyInto(out *StorageCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *StorageCluster) DeepCopy() *StorageCluster {
	if in == nil {
		return nil
	}
	out := new(StorageCluster)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *StorageClusterList) DeepCopyInto(out *StorageClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]StorageCluster, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *StorageClusterList) DeepCopy() *StorageClusterList {
	if in == nil {
		return nil
	}
	out := new(StorageClusterList)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
